stages:
  ingest_data:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/dataset.csv
    outs:
      - data/raw/dataset.csv

  preprocess_data:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/dataset.csv
    outs:
      - data/processed/processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/processed.csv
    outs:
      - data/processed/processed.csv

  train_model:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/processed.csv
    outs:
      - models/model.pkl

  evaluate_model:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed/processed.csv
    outs:
      - evaluation_results.txt
