stages:
  ingest_data:
    cmd: python main.py
    deps:
      - src/data_ingestion.py
      - data/raw/dataset.csv
    outs:
      - data/raw/dataset.csv

  preprocess_data:
    cmd: python main.py
    deps:
      - src/data_preprocessing.py
      - data/raw/dataset.csv
    outs:
      - data/processed/preprocessed.csv  # Renamed output file

  feature_engineering:
    cmd: python main.py
    deps:
      - src/feature_engineering.py
      - data/processed/preprocessed.csv  # Changed to the new output file
    outs:
      - data/processed/features.csv  # New output file for feature engineering

  train_model:
    cmd: python main.py
    deps:
      - src/model_training.py
      - data/processed/features.csv  # Changed to new features file
    outs:
      - models/model.pkl

  evaluate_model:
    cmd: python main.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed/features.csv  # Changed to new features file
    outs:
      - evaluation_results.txt
