stages:
  run_pipeline:
    cmd: python main.py
    deps:
      - main.py
      - src/data_ingestion.py
      - src/data_preprocessing.py
      - src/feature_engineering.py
      - src/model_training.py
      - src/model_evaluation.py
      - data/raw/dataset.csv
    outs:
      - data/processed/processed.csv
      - models/model.pkl
      - evaluation_results.txt
